#!/usr/bin/env python3
import os, sys, time, socket, subprocess, shutil, signal

BUILD_DIR = "/home/neo/CSC_DB/db2026/build"
SERVER_BIN = os.path.join(BUILD_DIR, "bin", "rmdb")
DB_NAME = "test_agg_m10"
DB_DIR = os.path.join(BUILD_DIR, "test_dbs", DB_NAME)
PORT = 8765

def send_sql(sql):
    sql = sql.strip()
    if not sql.endswith(';'):
        sql += ';'
    payload = sql.encode('utf-8') + b'\x00'
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(10)
    s.connect(("127.0.0.1", PORT))
    s.sendall(payload)
    data = b""
    while True:
        try:
            chunk = s.recv(8192)
            if not chunk:
                break
            data += chunk
            if b'\x00' in data:
                break
        except socket.timeout:
            break
    s.close()
    parts = data.split(b'\x00')
    return parts[0].decode('utf-8', errors='replace') if parts else ""

if os.path.isdir(DB_DIR):
    shutil.rmtree(DB_DIR)

os.makedirs(os.path.join(BUILD_DIR, "test_dbs"), exist_ok=True)
proc = subprocess.Popen(
    [SERVER_BIN, os.path.join("test_dbs", DB_NAME)],
    cwd=BUILD_DIR,
    stdout=open(os.devnull, "w"),
    stderr=open(os.devnull, "w")
)
time.sleep(2)

sql_count = 0
failures = []

def run(sql, check_fn=None, desc=""):
    global sql_count
    sql_count += 1
    try:
        r = send_sql(sql)
    except Exception as e:
        failures.append((sql_count, desc, sql, str(e)))
        print(f"[FAIL@{sql_count}] {desc}: {e}")
        return ""
    if check_fn and not check_fn(r):
        failures.append((sql_count, desc, sql, r[:200]))
        print(f"[FAIL@{sql_count}] {desc}")
    return r

run("CREATE TABLE t (id INT, score FLOAT, name CHAR(20), category CHAR(10));")
run("INSERT INTO t VALUES (1, 50.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (2, 51.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (3, 53.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (4, 54.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (5, 56.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (6, 57.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (7, 59.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (8, 57.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (9, 58.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (10, 60.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (11, 61.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (12, 63.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (13, 64.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (14, 66.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (15, 64.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (16, 65.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (17, 67.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (18, 68.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (19, 70.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (20, 71.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (21, 73.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (22, 71.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (23, 72.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (24, 74.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (25, 75.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (26, 77.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (27, 78.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (28, 80.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (29, 78.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (30, 79.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (31, 81.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (32, 82.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (33, 84.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (34, 85.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (35, 87.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (36, 85.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (37, 86.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (38, 88.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (39, 89.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (40, 91.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (41, 92.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (42, 94.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (43, 92.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (44, 93.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (45, 95.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (46, 96.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (47, 98.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (48, 99.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (49, 101.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (50, 99.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (51, 50.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (52, 52.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (53, 53.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (54, 55.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (55, 56.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (56, 58.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (57, 56.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (58, 57.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (59, 59.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (60, 60.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (61, 62.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (62, 63.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (63, 65.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (64, 63.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (65, 64.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (66, 66.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (67, 67.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (68, 69.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (69, 70.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (70, 72.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (71, 70.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (72, 71.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (73, 73.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (74, 74.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (75, 76.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (76, 77.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (77, 79.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (78, 77.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (79, 78.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (80, 80.0, 'Jack', 'CS');")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 50 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 0 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 50;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 60;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 51 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 1 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 51;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 61;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 52 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 2 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 52;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 62;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 53 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 3 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 53;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 63;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 54 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 4 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 54;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 64;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 55 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 5 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 55;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 65;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 56 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 6 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 56;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 66;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 57 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 7 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 57;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 67;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 58 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 8 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 58;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 68;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 59 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 9 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 59;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 69;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 60 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 10 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 60;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 70;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 61 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 11 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 61;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 71;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 62 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 12 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 62;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 72;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 63 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 13 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 63;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 73;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 64 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 14 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 64;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 74;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 65 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 15 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 65;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 75;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 66 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 16 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 66;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 76;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 67 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 17 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 67;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 77;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 68 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 18 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 68;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 78;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 69 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 19 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 69;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 79;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 70 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 20 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 50;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 60;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 71 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 21 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 51;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 61;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 72 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 22 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 52;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 62;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 73 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 23 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 53;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 63;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 74 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 24 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 54;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 64;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 75 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 25 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 55;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 65;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 76 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 26 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 56;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 66;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 77 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 27 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 57;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 67;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 78 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 28 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 58;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 68;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 79 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 29 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 59;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 69;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 50 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 30 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 60;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 70;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 51 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 31 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 61;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 71;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 52 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 32 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 62;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 72;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 53 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 33 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 63;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 73;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 54 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 34 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 64;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 74;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 55 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 35 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 65;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 75;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 56 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 36 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 66;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 76;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 57 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 37 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 67;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 77;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 58 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 38 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 68;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 78;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 59 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 39 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 69;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 79;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 60 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 0 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 50;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 60;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 61 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 1 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 51;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 61;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 62 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 2 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 52;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 62;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 63 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 3 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 53;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 63;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 64 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 4 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 54;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 64;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 65 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 5 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 55;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 65;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 66 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 6 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 56;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 66;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 67 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 7 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 57;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 67;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 68 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 8 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 58;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 68;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 69 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 9 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 59;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 69;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 70 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 10 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 60;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 70;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 71 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 11 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 61;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 71;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 72 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 12 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 62;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 72;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 73 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 13 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 63;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 73;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 74 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 14 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 64;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 74;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 75 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 15 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 65;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 75;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 76 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 16 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 66;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 76;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 77 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 17 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 67;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 77;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 78 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 18 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 68;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 78;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 79 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 19 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 69;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 79;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 50 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 20 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 50;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 60;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 51 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 21 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 51;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 61;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 52 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 22 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 52;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 62;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 53 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 23 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 53;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 63;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 54 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 24 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 54;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 64;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 55 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 25 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 55;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 65;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 56 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 26 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 56;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 66;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 57 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 27 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 57;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 67;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 58 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 28 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 58;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 68;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 59 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 29 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 59;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 69;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 60 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 30 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 60;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 70;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 61 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 31 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 61;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 71;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 62 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 32 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 62;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 72;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 63 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 33 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 63;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 73;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 64 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 34 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 64;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 74;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 65 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 35 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 65;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 75;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 66 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 36 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 66;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 76;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 67 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 37 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 67;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 77;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 68 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 38 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 68;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 78;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 69 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 39 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 69;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 79;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 70 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 0 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 50;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 60;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 71 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 1 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 51;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 61;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 72 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 2 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 52;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 62;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 73 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 3 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 53;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 63;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 74 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 4 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 54;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 64;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 75 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 5 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 55;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 65;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 76 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 6 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 56;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 66;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 77 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 7 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 57;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 67;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 78 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 8 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 58;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 68;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 79 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 9 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 59;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 69;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 50 ORDER BY score LIMIT 1;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 10 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 60;")
run("SELECT COUNT(*) FROM t WHERE name = 'Alice' AND score > 70;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 1 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 51 ORDER BY score LIMIT 2;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 11 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 61;")
run("SELECT COUNT(*) FROM t WHERE name = 'Bob' AND score > 71;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 2 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 52 ORDER BY score LIMIT 3;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 12 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 62;")
run("SELECT COUNT(*) FROM t WHERE name = 'Charlie' AND score > 72;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 3 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 53 ORDER BY score LIMIT 4;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 13 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 63;")
run("SELECT COUNT(*) FROM t WHERE name = 'David' AND score > 73;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 4 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 54 ORDER BY score LIMIT 5;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 14 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 64;")
run("SELECT COUNT(*) FROM t WHERE name = 'Eve' AND score > 74;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 5 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 3;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 1;")
run("SELECT * FROM t WHERE score > 55 ORDER BY score LIMIT 6;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 15 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 65;")
run("SELECT COUNT(*) FROM t WHERE name = 'Frank' AND score > 75;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Math';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 6 OFFSET 0;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 4;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 2;")
run("SELECT * FROM t WHERE score > 56 ORDER BY score LIMIT 7;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 16 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 66;")
run("SELECT COUNT(*) FROM t WHERE name = 'Grace' AND score > 76;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Physics';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 7 OFFSET 1;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 3;")
run("SELECT * FROM t WHERE score > 57 ORDER BY score LIMIT 8;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 17 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 67;")
run("SELECT COUNT(*) FROM t WHERE name = 'Henry' AND score > 77;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Chemistry';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 8 OFFSET 2;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 2;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 4;")
run("SELECT * FROM t WHERE score > 58 ORDER BY score LIMIT 9;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 18 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 68;")
run("SELECT COUNT(*) FROM t WHERE name = 'Ivy' AND score > 78;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'Biology';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 9 OFFSET 3;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 3;")
run("SELECT COUNT(*) AS total, MAX(score) AS mx, MIN(score) AS mn, SUM(score) AS sm, AVG(score) AS av FROM t;")
run("SELECT category, COUNT(*) AS cnt, AVG(score) AS av FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score), MIN(score) FROM t GROUP BY name ORDER BY MAX(score) DESC LIMIT 5;")
run("SELECT * FROM t WHERE score > 59 ORDER BY score LIMIT 10;")
run("SELECT category, COUNT(*), SUM(score) FROM t WHERE id > 19 GROUP BY category;")
run("SELECT name, AVG(score) FROM t GROUP BY name HAVING AVG(score) > 69;")
run("SELECT COUNT(*) FROM t WHERE name = 'Jack' AND score > 79;")
run("SELECT MAX(score), MIN(score), AVG(score) FROM t WHERE category = 'CS';")
run("SELECT id, score, name FROM t ORDER BY category, score DESC LIMIT 10 OFFSET 4;")
run("SELECT category, name, COUNT(*), MAX(score) FROM t GROUP BY category, name ORDER BY category LIMIT 1;")
run("DROP TABLE t;")
proc.send_signal(signal.SIGINT)
try:
    proc.wait(timeout=5)
except:
    proc.kill()

if failures:
    print(f"\nFAILED: {len(failures)} out of {sql_count} SQL")
    for idx, desc, sql, resp in failures[:5]:
        print(f"  @{idx} {desc}: {sql[:80]}...")
        print(f"    -> {resp[:120]}")
    sys.exit(1)
else:
    print(f"PASS: {sql_count} SQL executed, 0 failures")
