#!/usr/bin/env python3
import os, sys, time, socket, subprocess, shutil, signal

BUILD_DIR = "/home/neo/CSC_DB/db2026/build"
SERVER_BIN = os.path.join(BUILD_DIR, "bin", "rmdb")
DB_NAME = "test_agg_m05"
DB_DIR = os.path.join(BUILD_DIR, "test_dbs", DB_NAME)
PORT = 8765

def send_sql(sql):
    sql = sql.strip()
    if not sql.endswith(';'):
        sql += ';'
    payload = sql.encode('utf-8') + b'\x00'
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(10)
    s.connect(("127.0.0.1", PORT))
    s.sendall(payload)
    data = b""
    while True:
        try:
            chunk = s.recv(8192)
            if not chunk:
                break
            data += chunk
            if b'\x00' in data:
                break
        except socket.timeout:
            break
    s.close()
    parts = data.split(b'\x00')
    return parts[0].decode('utf-8', errors='replace') if parts else ""

if os.path.isdir(DB_DIR):
    shutil.rmtree(DB_DIR)

os.makedirs(os.path.join(BUILD_DIR, "test_dbs"), exist_ok=True)
proc = subprocess.Popen(
    [SERVER_BIN, os.path.join("test_dbs", DB_NAME)],
    cwd=BUILD_DIR,
    stdout=open(os.devnull, "w"),
    stderr=open(os.devnull, "w")
)
time.sleep(2)

sql_count = 0
failures = []

def run(sql, check_fn=None, desc=""):
    global sql_count
    sql_count += 1
    try:
        r = send_sql(sql)
    except Exception as e:
        failures.append((sql_count, desc, sql, str(e)))
        print(f"[FAIL@{sql_count}] {desc}: {e}")
        return ""
    if check_fn and not check_fn(r):
        failures.append((sql_count, desc, sql, r[:200]))
        print(f"[FAIL@{sql_count}] {desc}")
    return r

run("CREATE TABLE t (id INT, score FLOAT, name CHAR(20), category CHAR(10));")
run("INSERT INTO t VALUES (1, 50.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (2, 51.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (3, 53.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (4, 54.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (5, 56.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (6, 57.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (7, 59.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (8, 57.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (9, 58.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (10, 60.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (11, 61.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (12, 63.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (13, 64.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (14, 66.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (15, 64.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (16, 65.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (17, 67.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (18, 68.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (19, 70.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (20, 71.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (21, 73.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (22, 71.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (23, 72.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (24, 74.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (25, 75.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (26, 77.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (27, 78.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (28, 80.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (29, 78.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (30, 79.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (31, 81.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (32, 82.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (33, 84.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (34, 85.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (35, 87.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (36, 85.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (37, 86.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (38, 88.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (39, 89.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (40, 91.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (41, 92.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (42, 94.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (43, 92.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (44, 93.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (45, 95.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (46, 96.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (47, 98.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (48, 99.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (49, 101.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (50, 99.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (51, 50.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (52, 52.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (53, 53.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (54, 55.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (55, 56.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (56, 58.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (57, 56.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (58, 57.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (59, 59.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (60, 60.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (61, 62.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (62, 63.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (63, 65.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (64, 63.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (65, 64.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (66, 66.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (67, 67.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (68, 69.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (69, 70.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (70, 72.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (71, 70.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (72, 71.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (73, 73.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (74, 74.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (75, 76.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (76, 77.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (77, 79.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (78, 77.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (79, 78.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (80, 80.0, 'Jack', 'CS');")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 50;")
run("SELECT COUNT(*) FROM t WHERE score > 50 AND id > 0;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 1 AND 20;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 51;")
run("SELECT COUNT(*) FROM t WHERE score > 51 AND id > 1;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 2 AND 21;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 52;")
run("SELECT COUNT(*) FROM t WHERE score > 52 AND id > 2;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 3 AND 22;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 53;")
run("SELECT COUNT(*) FROM t WHERE score > 53 AND id > 3;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 4 AND 23;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 54;")
run("SELECT COUNT(*) FROM t WHERE score > 54 AND id > 4;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 5 AND 24;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 55;")
run("SELECT COUNT(*) FROM t WHERE score > 55 AND id > 5;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 6 AND 25;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 56;")
run("SELECT COUNT(*) FROM t WHERE score > 56 AND id > 6;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 7 AND 26;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 57;")
run("SELECT COUNT(*) FROM t WHERE score > 57 AND id > 7;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 8 AND 27;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 58;")
run("SELECT COUNT(*) FROM t WHERE score > 58 AND id > 8;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 9 AND 28;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 59;")
run("SELECT COUNT(*) FROM t WHERE score > 59 AND id > 9;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 10 AND 29;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 60;")
run("SELECT COUNT(*) FROM t WHERE score > 60 AND id > 10;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 11 AND 30;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 61;")
run("SELECT COUNT(*) FROM t WHERE score > 61 AND id > 11;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 12 AND 31;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 62;")
run("SELECT COUNT(*) FROM t WHERE score > 62 AND id > 12;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 13 AND 32;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 63;")
run("SELECT COUNT(*) FROM t WHERE score > 63 AND id > 13;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 14 AND 33;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 64;")
run("SELECT COUNT(*) FROM t WHERE score > 64 AND id > 14;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 15 AND 34;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 65;")
run("SELECT COUNT(*) FROM t WHERE score > 65 AND id > 15;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 16 AND 35;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 66;")
run("SELECT COUNT(*) FROM t WHERE score > 66 AND id > 16;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 17 AND 36;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 67;")
run("SELECT COUNT(*) FROM t WHERE score > 67 AND id > 17;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 18 AND 37;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 68;")
run("SELECT COUNT(*) FROM t WHERE score > 68 AND id > 18;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 19 AND 38;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 69;")
run("SELECT COUNT(*) FROM t WHERE score > 69 AND id > 19;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 20 AND 39;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 70;")
run("SELECT COUNT(*) FROM t WHERE score > 50 AND id > 20;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 21 AND 40;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 71;")
run("SELECT COUNT(*) FROM t WHERE score > 51 AND id > 21;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 22 AND 41;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 72;")
run("SELECT COUNT(*) FROM t WHERE score > 52 AND id > 22;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 23 AND 42;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 73;")
run("SELECT COUNT(*) FROM t WHERE score > 53 AND id > 23;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 24 AND 43;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 74;")
run("SELECT COUNT(*) FROM t WHERE score > 54 AND id > 24;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 25 AND 44;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 75;")
run("SELECT COUNT(*) FROM t WHERE score > 55 AND id > 25;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 26 AND 45;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 76;")
run("SELECT COUNT(*) FROM t WHERE score > 56 AND id > 26;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 27 AND 46;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 77;")
run("SELECT COUNT(*) FROM t WHERE score > 57 AND id > 27;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 28 AND 47;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 78;")
run("SELECT COUNT(*) FROM t WHERE score > 58 AND id > 28;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 29 AND 48;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 79;")
run("SELECT COUNT(*) FROM t WHERE score > 59 AND id > 29;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 30 AND 49;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 50;")
run("SELECT COUNT(*) FROM t WHERE score > 60 AND id > 30;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 31 AND 50;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 51;")
run("SELECT COUNT(*) FROM t WHERE score > 61 AND id > 31;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 32 AND 51;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 52;")
run("SELECT COUNT(*) FROM t WHERE score > 62 AND id > 32;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 33 AND 52;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 53;")
run("SELECT COUNT(*) FROM t WHERE score > 63 AND id > 33;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 34 AND 53;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 54;")
run("SELECT COUNT(*) FROM t WHERE score > 64 AND id > 34;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 35 AND 54;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 55;")
run("SELECT COUNT(*) FROM t WHERE score > 65 AND id > 35;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 36 AND 55;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 56;")
run("SELECT COUNT(*) FROM t WHERE score > 66 AND id > 36;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 37 AND 56;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 57;")
run("SELECT COUNT(*) FROM t WHERE score > 67 AND id > 37;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 38 AND 57;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 58;")
run("SELECT COUNT(*) FROM t WHERE score > 68 AND id > 38;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 39 AND 58;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 59;")
run("SELECT COUNT(*) FROM t WHERE score > 69 AND id > 39;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 40 AND 59;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 60;")
run("SELECT COUNT(*) FROM t WHERE score > 50 AND id > 0;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 1 AND 20;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 61;")
run("SELECT COUNT(*) FROM t WHERE score > 51 AND id > 1;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 2 AND 21;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 62;")
run("SELECT COUNT(*) FROM t WHERE score > 52 AND id > 2;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 3 AND 22;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 63;")
run("SELECT COUNT(*) FROM t WHERE score > 53 AND id > 3;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 4 AND 23;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 64;")
run("SELECT COUNT(*) FROM t WHERE score > 54 AND id > 4;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 5 AND 24;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 65;")
run("SELECT COUNT(*) FROM t WHERE score > 55 AND id > 5;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 6 AND 25;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 66;")
run("SELECT COUNT(*) FROM t WHERE score > 56 AND id > 6;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 7 AND 26;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 67;")
run("SELECT COUNT(*) FROM t WHERE score > 57 AND id > 7;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 8 AND 27;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 68;")
run("SELECT COUNT(*) FROM t WHERE score > 58 AND id > 8;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 9 AND 28;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 69;")
run("SELECT COUNT(*) FROM t WHERE score > 59 AND id > 9;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 10 AND 29;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 70;")
run("SELECT COUNT(*) FROM t WHERE score > 60 AND id > 10;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 11 AND 30;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 71;")
run("SELECT COUNT(*) FROM t WHERE score > 61 AND id > 11;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 12 AND 31;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 72;")
run("SELECT COUNT(*) FROM t WHERE score > 62 AND id > 12;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 13 AND 32;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 73;")
run("SELECT COUNT(*) FROM t WHERE score > 63 AND id > 13;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 14 AND 33;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 74;")
run("SELECT COUNT(*) FROM t WHERE score > 64 AND id > 14;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 15 AND 34;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 75;")
run("SELECT COUNT(*) FROM t WHERE score > 65 AND id > 15;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 16 AND 35;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 76;")
run("SELECT COUNT(*) FROM t WHERE score > 66 AND id > 16;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 17 AND 36;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 77;")
run("SELECT COUNT(*) FROM t WHERE score > 67 AND id > 17;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 18 AND 37;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 78;")
run("SELECT COUNT(*) FROM t WHERE score > 68 AND id > 18;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 19 AND 38;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 79;")
run("SELECT COUNT(*) FROM t WHERE score > 69 AND id > 19;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 20 AND 39;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 50;")
run("SELECT COUNT(*) FROM t WHERE score > 50 AND id > 20;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 21 AND 40;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 51;")
run("SELECT COUNT(*) FROM t WHERE score > 51 AND id > 21;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 22 AND 41;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 52;")
run("SELECT COUNT(*) FROM t WHERE score > 52 AND id > 22;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 23 AND 42;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 53;")
run("SELECT COUNT(*) FROM t WHERE score > 53 AND id > 23;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 24 AND 43;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 54;")
run("SELECT COUNT(*) FROM t WHERE score > 54 AND id > 24;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 25 AND 44;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 55;")
run("SELECT COUNT(*) FROM t WHERE score > 55 AND id > 25;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 26 AND 45;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 56;")
run("SELECT COUNT(*) FROM t WHERE score > 56 AND id > 26;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 27 AND 46;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 57;")
run("SELECT COUNT(*) FROM t WHERE score > 57 AND id > 27;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 28 AND 47;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 58;")
run("SELECT COUNT(*) FROM t WHERE score > 58 AND id > 28;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 29 AND 48;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 59;")
run("SELECT COUNT(*) FROM t WHERE score > 59 AND id > 29;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 30 AND 49;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 60;")
run("SELECT COUNT(*) FROM t WHERE score > 60 AND id > 30;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 31 AND 50;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 61;")
run("SELECT COUNT(*) FROM t WHERE score > 61 AND id > 31;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 32 AND 51;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 62;")
run("SELECT COUNT(*) FROM t WHERE score > 62 AND id > 32;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 33 AND 52;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 63;")
run("SELECT COUNT(*) FROM t WHERE score > 63 AND id > 33;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 34 AND 53;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 64;")
run("SELECT COUNT(*) FROM t WHERE score > 64 AND id > 34;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 35 AND 54;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 65;")
run("SELECT COUNT(*) FROM t WHERE score > 65 AND id > 35;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 36 AND 55;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 66;")
run("SELECT COUNT(*) FROM t WHERE score > 66 AND id > 36;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 37 AND 56;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 67;")
run("SELECT COUNT(*) FROM t WHERE score > 67 AND id > 37;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 38 AND 57;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 68;")
run("SELECT COUNT(*) FROM t WHERE score > 68 AND id > 38;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 39 AND 58;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 69;")
run("SELECT COUNT(*) FROM t WHERE score > 69 AND id > 39;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 40 AND 59;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 70;")
run("SELECT COUNT(*) FROM t WHERE score > 50 AND id > 0;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 1 AND 20;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 71;")
run("SELECT COUNT(*) FROM t WHERE score > 51 AND id > 1;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 2 AND 21;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 72;")
run("SELECT COUNT(*) FROM t WHERE score > 52 AND id > 2;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 3 AND 22;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 73;")
run("SELECT COUNT(*) FROM t WHERE score > 53 AND id > 3;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 4 AND 23;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 74;")
run("SELECT COUNT(*) FROM t WHERE score > 54 AND id > 4;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 5 AND 24;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 75;")
run("SELECT COUNT(*) FROM t WHERE score > 55 AND id > 5;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 6 AND 25;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 76;")
run("SELECT COUNT(*) FROM t WHERE score > 56 AND id > 6;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 7 AND 26;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 77;")
run("SELECT COUNT(*) FROM t WHERE score > 57 AND id > 7;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 8 AND 27;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 78;")
run("SELECT COUNT(*) FROM t WHERE score > 58 AND id > 8;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 9 AND 28;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 79;")
run("SELECT COUNT(*) FROM t WHERE score > 59 AND id > 9;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 10 AND 29;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 50;")
run("SELECT COUNT(*) FROM t WHERE score > 60 AND id > 10;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Alice';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 11 AND 30;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 51;")
run("SELECT COUNT(*) FROM t WHERE score > 61 AND id > 11;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Bob';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 12 AND 31;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 52;")
run("SELECT COUNT(*) FROM t WHERE score > 62 AND id > 12;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Charlie';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 13 AND 32;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 53;")
run("SELECT COUNT(*) FROM t WHERE score > 63 AND id > 13;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'David';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 14 AND 33;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 54;")
run("SELECT COUNT(*) FROM t WHERE score > 64 AND id > 14;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Eve';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 15 AND 34;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 55;")
run("SELECT COUNT(*) FROM t WHERE score > 65 AND id > 15;")
run("SELECT MAX(score) FROM t WHERE category = 'Math' OR name = 'Frank';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 16 AND 35;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 56;")
run("SELECT COUNT(*) FROM t WHERE score > 66 AND id > 16;")
run("SELECT MAX(score) FROM t WHERE category = 'Physics' OR name = 'Grace';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 17 AND 36;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 57;")
run("SELECT COUNT(*) FROM t WHERE score > 67 AND id > 17;")
run("SELECT MAX(score) FROM t WHERE category = 'Chemistry' OR name = 'Henry';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 18 AND 37;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 58;")
run("SELECT COUNT(*) FROM t WHERE score > 68 AND id > 18;")
run("SELECT MAX(score) FROM t WHERE category = 'Biology' OR name = 'Ivy';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 19 AND 38;")
run("SELECT COUNT(*) AS total FROM t;")
run("SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM t;")
run("SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM t;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name;")
run("SELECT category, AVG(score) AS av, SUM(score) AS sm FROM t GROUP BY category;")
run("SELECT COUNT(*) AS c, MAX(id) AS m FROM t WHERE score > 59;")
run("SELECT COUNT(*) FROM t WHERE score > 69 AND id > 19;")
run("SELECT MAX(score) FROM t WHERE category = 'CS' OR name = 'Jack';")
run("SELECT AVG(score) FROM t WHERE id BETWEEN 20 AND 39;")
run("DROP TABLE t;")
proc.send_signal(signal.SIGINT)
try:
    proc.wait(timeout=5)
except:
    proc.kill()

if failures:
    print(f"\nFAILED: {len(failures)} out of {sql_count} SQL")
    for idx, desc, sql, resp in failures[:5]:
        print(f"  @{idx} {desc}: {sql[:80]}...")
        print(f"    -> {resp[:120]}")
    sys.exit(1)
else:
    print(f"PASS: {sql_count} SQL executed, 0 failures")
