#!/usr/bin/env python3
import os, sys, time, socket, subprocess, shutil, signal

BUILD_DIR = "/home/neo/CSC_DB/db2026/build"
SERVER_BIN = os.path.join(BUILD_DIR, "bin", "rmdb")
DB_NAME = "test_agg_m03"
DB_DIR = os.path.join(BUILD_DIR, "test_dbs", DB_NAME)
PORT = 8765

def send_sql(sql):
    sql = sql.strip()
    if not sql.endswith(';'):
        sql += ';'
    payload = sql.encode('utf-8') + b'\x00'
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(10)
    s.connect(("127.0.0.1", PORT))
    s.sendall(payload)
    data = b""
    while True:
        try:
            chunk = s.recv(8192)
            if not chunk:
                break
            data += chunk
            if b'\x00' in data:
                break
        except socket.timeout:
            break
    s.close()
    parts = data.split(b'\x00')
    return parts[0].decode('utf-8', errors='replace') if parts else ""

if os.path.isdir(DB_DIR):
    shutil.rmtree(DB_DIR)

os.makedirs(os.path.join(BUILD_DIR, "test_dbs"), exist_ok=True)
proc = subprocess.Popen(
    [SERVER_BIN, os.path.join("test_dbs", DB_NAME)],
    cwd=BUILD_DIR,
    stdout=open(os.devnull, "w"),
    stderr=open(os.devnull, "w")
)
time.sleep(2)

sql_count = 0
failures = []

def run(sql, check_fn=None, desc=""):
    global sql_count
    sql_count += 1
    try:
        r = send_sql(sql)
    except Exception as e:
        failures.append((sql_count, desc, sql, str(e)))
        print(f"[FAIL@{sql_count}] {desc}: {e}")
        return ""
    if check_fn and not check_fn(r):
        failures.append((sql_count, desc, sql, r[:200]))
        print(f"[FAIL@{sql_count}] {desc}")
    return r

run("CREATE TABLE t (id INT, score FLOAT, name CHAR(20), category CHAR(10));")
run("INSERT INTO t VALUES (1, 50.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (2, 51.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (3, 53.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (4, 54.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (5, 56.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (6, 57.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (7, 59.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (8, 57.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (9, 58.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (10, 60.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (11, 61.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (12, 63.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (13, 64.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (14, 66.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (15, 64.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (16, 65.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (17, 67.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (18, 68.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (19, 70.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (20, 71.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (21, 73.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (22, 71.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (23, 72.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (24, 74.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (25, 75.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (26, 77.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (27, 78.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (28, 80.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (29, 78.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (30, 79.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (31, 81.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (32, 82.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (33, 84.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (34, 85.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (35, 87.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (36, 85.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (37, 86.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (38, 88.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (39, 89.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (40, 91.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (41, 92.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (42, 94.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (43, 92.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (44, 93.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (45, 95.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (46, 96.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (47, 98.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (48, 99.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (49, 101.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (50, 99.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (51, 50.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (52, 52.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (53, 53.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (54, 55.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (55, 56.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (56, 58.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (57, 56.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (58, 57.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (59, 59.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (60, 60.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (61, 62.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (62, 63.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (63, 65.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (64, 63.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (65, 64.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (66, 66.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (67, 67.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (68, 69.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (69, 70.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (70, 72.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (71, 70.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (72, 71.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (73, 73.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (74, 74.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (75, 76.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (76, 77.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (77, 79.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (78, 77.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (79, 78.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (80, 80.0, 'Jack', 'CS');")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 1;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 1;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 2;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 2;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 3;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 3;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 4;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 4;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 5;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 5;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 6;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 6;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 7;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 7;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 8;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 8;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 9;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 9;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 10;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 10;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 11;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 11;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 12;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 12;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 13;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 13;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 14;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 14;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 15;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 15;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 16;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 16;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 17;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 17;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 18;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 18;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 19;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 19;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 20;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 20;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 1;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 21;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 2;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 22;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 3;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 23;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 4;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 24;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 5;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 25;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 6;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 26;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 7;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 27;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 8;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 28;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 9;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 29;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 10;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 30;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 11;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 1;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 12;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 2;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 13;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 3;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 14;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 4;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 15;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 5;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 16;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 6;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 17;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 7;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 18;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 8;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 19;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 9;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 20;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 10;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 1;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 11;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 2;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 12;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 3;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 13;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 4;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 14;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 5;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 15;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 6;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 16;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 7;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 17;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 8;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 18;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 9;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 19;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 10;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 20;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 11;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 21;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 12;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 22;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 13;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 23;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 14;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 24;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 15;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 25;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 16;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 26;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 17;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 27;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 18;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 28;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 19;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 29;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 20;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 30;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 1;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 1;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 2;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 2;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 3;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 3;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 4;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 4;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 5;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 5;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 6;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 6;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 7;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 7;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 8;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 8;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 9;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 9;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 10;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 10;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 11;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 11;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 12;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 12;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 13;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 13;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 14;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 14;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 15;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 15;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 16;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 16;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 17;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 17;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 18;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 18;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 19;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 19;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 20;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 20;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 1;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 21;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 2;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 22;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 3;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 23;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 4;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 24;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 5;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 25;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 6;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 26;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 7;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 27;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 8;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 28;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 9;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 29;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 10;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 30;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 11;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 1;")
run("SELECT * FROM t ORDER BY id LIMIT 1;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 12;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 2;")
run("SELECT * FROM t ORDER BY id LIMIT 2;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 13;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 3;")
run("SELECT * FROM t ORDER BY id LIMIT 3;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 14;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 4;")
run("SELECT * FROM t ORDER BY id LIMIT 4;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 15;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 5;")
run("SELECT * FROM t ORDER BY id LIMIT 5;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 16;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 6;")
run("SELECT * FROM t ORDER BY id LIMIT 6;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 17;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 7;")
run("SELECT * FROM t ORDER BY id LIMIT 7;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 18;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 8;")
run("SELECT * FROM t ORDER BY id LIMIT 8;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 19;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 9;")
run("SELECT * FROM t ORDER BY id LIMIT 9;")
run("SELECT id, score FROM t ORDER BY score;")
run("SELECT id, score FROM t ORDER BY score DESC;")
run("SELECT name, score FROM t ORDER BY name;")
run("SELECT category, score FROM t ORDER BY category, score DESC;")
run("SELECT id, name, score FROM t ORDER BY id DESC;")
run("SELECT * FROM t ORDER BY score, id;")
run("SELECT category, COUNT(*) FROM t GROUP BY category ORDER BY COUNT(*) DESC;")
run("SELECT id, score FROM t ORDER BY score LIMIT 20;")
run("SELECT name, score FROM t ORDER BY score DESC LIMIT 10;")
run("SELECT * FROM t ORDER BY id LIMIT 10;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 1 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 2 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 3 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 4 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 5 OFFSET 4;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 6 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 7 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 8 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 9 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 10 OFFSET 4;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 1 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 2 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 3 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 4 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 5 OFFSET 4;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 6 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 7 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 8 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 9 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 10 OFFSET 4;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 1 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 2 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 3 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 4 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 5 OFFSET 4;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 6 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 7 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 8 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 9 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 10 OFFSET 4;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 1 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 2 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 3 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 4 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 5 OFFSET 4;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 6 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 7 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 8 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 9 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 10 OFFSET 4;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 1 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 2 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 3 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 4 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 5 OFFSET 4;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 6 OFFSET 0;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 7 OFFSET 1;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 8 OFFSET 2;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 9 OFFSET 3;")
run("SELECT * FROM t ORDER BY score DESC LIMIT 10 OFFSET 4;")
run("DROP TABLE t;")
proc.send_signal(signal.SIGINT)
try:
    proc.wait(timeout=5)
except:
    proc.kill()

if failures:
    print(f"\nFAILED: {len(failures)} out of {sql_count} SQL")
    for idx, desc, sql, resp in failures[:5]:
        print(f"  @{idx} {desc}: {sql[:80]}...")
        print(f"    -> {resp[:120]}")
    sys.exit(1)
else:
    print(f"PASS: {sql_count} SQL executed, 0 failures")
