#!/usr/bin/env python3
import os, sys, time, socket, subprocess, shutil, signal

BUILD_DIR = "/home/neo/CSC_DB/db2026/build"
SERVER_BIN = os.path.join(BUILD_DIR, "bin", "rmdb")
DB_NAME = "test_agg_m07"
DB_DIR = os.path.join(BUILD_DIR, "test_dbs", DB_NAME)
PORT = 8765

def send_sql(sql):
    sql = sql.strip()
    if not sql.endswith(';'):
        sql += ';'
    payload = sql.encode('utf-8') + b'\x00'
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(10)
    s.connect(("127.0.0.1", PORT))
    s.sendall(payload)
    data = b""
    while True:
        try:
            chunk = s.recv(8192)
            if not chunk:
                break
            data += chunk
            if b'\x00' in data:
                break
        except socket.timeout:
            break
    s.close()
    parts = data.split(b'\x00')
    return parts[0].decode('utf-8', errors='replace') if parts else ""

if os.path.isdir(DB_DIR):
    shutil.rmtree(DB_DIR)

os.makedirs(os.path.join(BUILD_DIR, "test_dbs"), exist_ok=True)
proc = subprocess.Popen(
    [SERVER_BIN, os.path.join("test_dbs", DB_NAME)],
    cwd=BUILD_DIR,
    stdout=open(os.devnull, "w"),
    stderr=open(os.devnull, "w")
)
time.sleep(2)

sql_count = 0
failures = []

def run(sql, check_fn=None, desc=""):
    global sql_count
    sql_count += 1
    try:
        r = send_sql(sql)
    except Exception as e:
        failures.append((sql_count, desc, sql, str(e)))
        print(f"[FAIL@{sql_count}] {desc}: {e}")
        return ""
    if check_fn and not check_fn(r):
        failures.append((sql_count, desc, sql, r[:200]))
        print(f"[FAIL@{sql_count}] {desc}")
    return r

run("CREATE TABLE t (id INT, score FLOAT, name CHAR(20), category CHAR(10));")
run("INSERT INTO t VALUES (1, 50.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (2, 51.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (3, 53.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (4, 54.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (5, 56.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (6, 57.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (7, 59.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (8, 57.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (9, 58.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (10, 60.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (11, 61.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (12, 63.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (13, 64.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (14, 66.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (15, 64.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (16, 65.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (17, 67.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (18, 68.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (19, 70.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (20, 71.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (21, 73.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (22, 71.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (23, 72.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (24, 74.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (25, 75.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (26, 77.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (27, 78.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (28, 80.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (29, 78.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (30, 79.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (31, 81.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (32, 82.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (33, 84.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (34, 85.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (35, 87.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (36, 85.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (37, 86.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (38, 88.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (39, 89.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (40, 91.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (41, 92.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (42, 94.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (43, 92.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (44, 93.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (45, 95.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (46, 96.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (47, 98.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (48, 99.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (49, 101.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (50, 99.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (51, 50.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (52, 52.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (53, 53.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (54, 55.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (55, 56.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (56, 58.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (57, 56.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (58, 57.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (59, 59.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (60, 60.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (61, 62.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (62, 63.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (63, 65.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (64, 63.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (65, 64.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (66, 66.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (67, 67.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (68, 69.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (69, 70.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (70, 72.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (71, 70.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (72, 71.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (73, 73.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (74, 74.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (75, 76.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (76, 77.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (77, 79.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (78, 77.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (79, 78.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (80, 80.0, 'Jack', 'CS');")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 60;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 50;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 200;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 61;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 51;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 201;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 62;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 52;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 202;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 63;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 53;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 203;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 64;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 54;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 204;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 65;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 55;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 205;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 66;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 56;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 206;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 67;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 57;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 207;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 68;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 58;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 208;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 69;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 59;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 209;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 70;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 60;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 210;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 71;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 61;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 211;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 72;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 62;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 212;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 73;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 63;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 213;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 74;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 64;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 214;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 75;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 65;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 215;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 76;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 66;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 216;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 77;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 67;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 217;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 78;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 68;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 218;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 79;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 69;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 219;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 80;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 50;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 220;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 81;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 51;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 221;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 82;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 52;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 222;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 83;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 53;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 223;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 84;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 54;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 224;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 85;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 55;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 225;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 86;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 56;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 226;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 87;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 57;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 227;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 88;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 58;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 228;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 89;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 59;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 229;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 60;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 60;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 230;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 61;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 61;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 231;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 62;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 62;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 232;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 63;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 63;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 233;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 64;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 64;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 234;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 65;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 65;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 235;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 66;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 66;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 236;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 67;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 67;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 237;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 68;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 68;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 238;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 69;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 69;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 239;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 70;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 50;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 240;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 71;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 51;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 241;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 72;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 52;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 242;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 73;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 53;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 243;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 74;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 54;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 244;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 75;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 55;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 245;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 76;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 56;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 246;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 77;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 57;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 247;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 78;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 58;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 248;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 79;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 59;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 249;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 80;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 60;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 250;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 81;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 61;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 251;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 82;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 62;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 252;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 83;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 63;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 253;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 84;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 64;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 254;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 85;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 65;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 255;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 86;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 66;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 256;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 87;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 67;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 257;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 88;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 68;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 258;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 89;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 69;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 259;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 60;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 50;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 260;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 61;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 51;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 261;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 62;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 52;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 262;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 63;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 53;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 263;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 64;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 54;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 264;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 65;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 55;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 265;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 66;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 56;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 266;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 67;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 57;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 267;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 68;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 58;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 268;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 69;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 59;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 269;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 70;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 60;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 270;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 71;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 61;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 271;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 72;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 62;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 272;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 73;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 63;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 273;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 74;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 64;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 274;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 75;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 65;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 275;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 76;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 66;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 276;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 77;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 67;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 277;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 78;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 68;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 278;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 79;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 69;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 279;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 80;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 50;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 280;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 81;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 51;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 281;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 82;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 52;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 282;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 83;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 53;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 283;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 84;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 54;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 284;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 85;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 55;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 285;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 86;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 56;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 286;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 87;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 57;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 287;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 88;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 58;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 288;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 89;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 59;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 289;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 60;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 60;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 290;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 61;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 61;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 291;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 62;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 62;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 292;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 63;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 63;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 293;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 64;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 64;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 294;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 5;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 65;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 65;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 295;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 6;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 66;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 66;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 296;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 7;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 67;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 2;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 67;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 297;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 8;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 68;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 3;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 68;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 298;")
run("SELECT category, name, COUNT(*) FROM t GROUP BY category, name;")
run("SELECT name, category, AVG(score) FROM t GROUP BY name, category;")
run("SELECT category, name, MAX(score), MIN(score) FROM t GROUP BY category, name;")
run("SELECT name, COUNT(*), SUM(score) FROM t GROUP BY name;")
run("SELECT category, COUNT(*), AVG(score) FROM t GROUP BY category;")
run("SELECT category, COUNT(*) AS cnt FROM t GROUP BY category HAVING cnt > 9;")
run("SELECT name, MAX(score) AS mx FROM t GROUP BY name HAVING mx > 69;")
run("SELECT category, name, COUNT(*) AS c FROM t GROUP BY category, name HAVING c >= 1;")
run("SELECT category, AVG(score) AS av FROM t GROUP BY category HAVING av > 69;")
run("SELECT name, SUM(score) AS sm FROM t GROUP BY name HAVING sm > 299;")
run("DROP TABLE t;")
proc.send_signal(signal.SIGINT)
try:
    proc.wait(timeout=5)
except:
    proc.kill()

if failures:
    print(f"\nFAILED: {len(failures)} out of {sql_count} SQL")
    for idx, desc, sql, resp in failures[:5]:
        print(f"  @{idx} {desc}: {sql[:80]}...")
        print(f"    -> {resp[:120]}")
    sys.exit(1)
else:
    print(f"PASS: {sql_count} SQL executed, 0 failures")
