#!/usr/bin/env python3
import os, sys, time, socket, subprocess, shutil, signal

BUILD_DIR = "/home/neo/CSC_DB/db2026/build"
SERVER_BIN = os.path.join(BUILD_DIR, "bin", "rmdb")
DB_NAME = "test_agg_m01"
DB_DIR = os.path.join(BUILD_DIR, "test_dbs", DB_NAME)
PORT = 8765

def send_sql(sql):
    sql = sql.strip()
    if not sql.endswith(';'):
        sql += ';'
    payload = sql.encode('utf-8') + b'\x00'
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(10)
    s.connect(("127.0.0.1", PORT))
    s.sendall(payload)
    data = b""
    while True:
        try:
            chunk = s.recv(8192)
            if not chunk:
                break
            data += chunk
            if b'\x00' in data:
                break
        except socket.timeout:
            break
    s.close()
    parts = data.split(b'\x00')
    return parts[0].decode('utf-8', errors='replace') if parts else ""

if os.path.isdir(DB_DIR):
    shutil.rmtree(DB_DIR)

os.makedirs(os.path.join(BUILD_DIR, "test_dbs"), exist_ok=True)
proc = subprocess.Popen(
    [SERVER_BIN, os.path.join("test_dbs", DB_NAME)],
    cwd=BUILD_DIR,
    stdout=open(os.devnull, "w"),
    stderr=open(os.devnull, "w")
)
time.sleep(2)

sql_count = 0
failures = []

def run(sql, check_fn=None, desc=""):
    global sql_count
    sql_count += 1
    try:
        r = send_sql(sql)
    except Exception as e:
        failures.append((sql_count, desc, sql, str(e)))
        print(f"[FAIL@{sql_count}] {desc}: {e}")
        return ""
    if check_fn and not check_fn(r):
        failures.append((sql_count, desc, sql, r[:200]))
        print(f"[FAIL@{sql_count}] {desc}")
    return r

run("CREATE TABLE t (id INT, score FLOAT, name CHAR(20), category CHAR(10));")
run("INSERT INTO t VALUES (1, 50.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (2, 51.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (3, 53.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (4, 54.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (5, 56.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (6, 57.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (7, 59.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (8, 57.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (9, 58.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (10, 60.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (11, 61.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (12, 63.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (13, 64.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (14, 66.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (15, 64.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (16, 65.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (17, 67.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (18, 68.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (19, 70.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (20, 71.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (21, 73.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (22, 71.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (23, 72.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (24, 74.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (25, 75.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (26, 77.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (27, 78.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (28, 80.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (29, 78.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (30, 79.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (31, 81.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (32, 82.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (33, 84.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (34, 85.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (35, 87.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (36, 85.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (37, 86.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (38, 88.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (39, 89.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (40, 91.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (41, 92.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (42, 94.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (43, 92.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (44, 93.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (45, 95.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (46, 96.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (47, 98.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (48, 99.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (49, 101.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (50, 99.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (51, 50.5, 'Alice', 'Math');")
run("INSERT INTO t VALUES (52, 52.0, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (53, 53.5, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (54, 55.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (55, 56.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (56, 58.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (57, 56.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (58, 57.5, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (59, 59.0, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (60, 60.5, 'Jack', 'CS');")
run("INSERT INTO t VALUES (61, 62.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (62, 63.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (63, 65.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (64, 63.0, 'David', 'Biology');")
run("INSERT INTO t VALUES (65, 64.5, 'Eve', 'CS');")
run("INSERT INTO t VALUES (66, 66.0, 'Frank', 'Math');")
run("INSERT INTO t VALUES (67, 67.5, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (68, 69.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (69, 70.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (70, 72.0, 'Jack', 'CS');")
run("INSERT INTO t VALUES (71, 70.0, 'Alice', 'Math');")
run("INSERT INTO t VALUES (72, 71.5, 'Bob', 'Physics');")
run("INSERT INTO t VALUES (73, 73.0, 'Charlie', 'Chemistry');")
run("INSERT INTO t VALUES (74, 74.5, 'David', 'Biology');")
run("INSERT INTO t VALUES (75, 76.0, 'Eve', 'CS');")
run("INSERT INTO t VALUES (76, 77.5, 'Frank', 'Math');")
run("INSERT INTO t VALUES (77, 79.0, 'Grace', 'Physics');")
run("INSERT INTO t VALUES (78, 77.0, 'Henry', 'Chemistry');")
run("INSERT INTO t VALUES (79, 78.5, 'Ivy', 'Biology');")
run("INSERT INTO t VALUES (80, 80.0, 'Jack', 'CS');")
run("SELECT COUNT(*) FROM t WHERE score > 60;")
run("SELECT MAX(score) FROM t WHERE id > 0;")
run("SELECT MIN(score) FROM t WHERE id <= 5;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 60 AND 80;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 61;")
run("SELECT MAX(score) FROM t WHERE id > 1;")
run("SELECT MIN(score) FROM t WHERE id <= 6;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 61 AND 81;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 62;")
run("SELECT MAX(score) FROM t WHERE id > 2;")
run("SELECT MIN(score) FROM t WHERE id <= 7;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 62 AND 82;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 63;")
run("SELECT MAX(score) FROM t WHERE id > 3;")
run("SELECT MIN(score) FROM t WHERE id <= 8;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 63 AND 83;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 64;")
run("SELECT MAX(score) FROM t WHERE id > 4;")
run("SELECT MIN(score) FROM t WHERE id <= 9;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 64 AND 84;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 65;")
run("SELECT MAX(score) FROM t WHERE id > 5;")
run("SELECT MIN(score) FROM t WHERE id <= 10;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 65 AND 85;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 66;")
run("SELECT MAX(score) FROM t WHERE id > 6;")
run("SELECT MIN(score) FROM t WHERE id <= 11;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 66 AND 86;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 67;")
run("SELECT MAX(score) FROM t WHERE id > 7;")
run("SELECT MIN(score) FROM t WHERE id <= 12;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 67 AND 87;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 68;")
run("SELECT MAX(score) FROM t WHERE id > 8;")
run("SELECT MIN(score) FROM t WHERE id <= 13;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 68 AND 88;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 69;")
run("SELECT MAX(score) FROM t WHERE id > 9;")
run("SELECT MIN(score) FROM t WHERE id <= 14;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 69 AND 89;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 70;")
run("SELECT MAX(score) FROM t WHERE id > 10;")
run("SELECT MIN(score) FROM t WHERE id <= 15;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 70 AND 90;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 71;")
run("SELECT MAX(score) FROM t WHERE id > 11;")
run("SELECT MIN(score) FROM t WHERE id <= 16;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 71 AND 91;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 72;")
run("SELECT MAX(score) FROM t WHERE id > 12;")
run("SELECT MIN(score) FROM t WHERE id <= 17;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 72 AND 92;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 73;")
run("SELECT MAX(score) FROM t WHERE id > 13;")
run("SELECT MIN(score) FROM t WHERE id <= 18;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 73 AND 93;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 74;")
run("SELECT MAX(score) FROM t WHERE id > 14;")
run("SELECT MIN(score) FROM t WHERE id <= 19;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 74 AND 94;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 75;")
run("SELECT MAX(score) FROM t WHERE id > 15;")
run("SELECT MIN(score) FROM t WHERE id <= 20;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 75 AND 95;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 76;")
run("SELECT MAX(score) FROM t WHERE id > 16;")
run("SELECT MIN(score) FROM t WHERE id <= 21;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 76 AND 96;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 77;")
run("SELECT MAX(score) FROM t WHERE id > 17;")
run("SELECT MIN(score) FROM t WHERE id <= 22;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 77 AND 97;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 78;")
run("SELECT MAX(score) FROM t WHERE id > 18;")
run("SELECT MIN(score) FROM t WHERE id <= 23;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 78 AND 98;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 79;")
run("SELECT MAX(score) FROM t WHERE id > 19;")
run("SELECT MIN(score) FROM t WHERE id <= 24;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 79 AND 99;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 80;")
run("SELECT MAX(score) FROM t WHERE id > 20;")
run("SELECT MIN(score) FROM t WHERE id <= 25;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 80 AND 100;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 81;")
run("SELECT MAX(score) FROM t WHERE id > 21;")
run("SELECT MIN(score) FROM t WHERE id <= 26;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 81 AND 101;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 82;")
run("SELECT MAX(score) FROM t WHERE id > 22;")
run("SELECT MIN(score) FROM t WHERE id <= 27;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 82 AND 102;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 83;")
run("SELECT MAX(score) FROM t WHERE id > 23;")
run("SELECT MIN(score) FROM t WHERE id <= 28;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 83 AND 103;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 84;")
run("SELECT MAX(score) FROM t WHERE id > 24;")
run("SELECT MIN(score) FROM t WHERE id <= 29;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 84 AND 104;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 85;")
run("SELECT MAX(score) FROM t WHERE id > 25;")
run("SELECT MIN(score) FROM t WHERE id <= 30;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 85 AND 105;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 86;")
run("SELECT MAX(score) FROM t WHERE id > 26;")
run("SELECT MIN(score) FROM t WHERE id <= 31;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 86 AND 106;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 87;")
run("SELECT MAX(score) FROM t WHERE id > 27;")
run("SELECT MIN(score) FROM t WHERE id <= 32;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 87 AND 107;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 88;")
run("SELECT MAX(score) FROM t WHERE id > 28;")
run("SELECT MIN(score) FROM t WHERE id <= 33;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 88 AND 108;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 89;")
run("SELECT MAX(score) FROM t WHERE id > 29;")
run("SELECT MIN(score) FROM t WHERE id <= 34;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 89 AND 109;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 90;")
run("SELECT MAX(score) FROM t WHERE id > 30;")
run("SELECT MIN(score) FROM t WHERE id <= 35;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 90 AND 110;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 91;")
run("SELECT MAX(score) FROM t WHERE id > 31;")
run("SELECT MIN(score) FROM t WHERE id <= 36;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 91 AND 111;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 92;")
run("SELECT MAX(score) FROM t WHERE id > 32;")
run("SELECT MIN(score) FROM t WHERE id <= 37;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 92 AND 112;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 93;")
run("SELECT MAX(score) FROM t WHERE id > 33;")
run("SELECT MIN(score) FROM t WHERE id <= 38;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 93 AND 113;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 94;")
run("SELECT MAX(score) FROM t WHERE id > 34;")
run("SELECT MIN(score) FROM t WHERE id <= 39;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 94 AND 114;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 95;")
run("SELECT MAX(score) FROM t WHERE id > 35;")
run("SELECT MIN(score) FROM t WHERE id <= 40;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 95 AND 115;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 96;")
run("SELECT MAX(score) FROM t WHERE id > 36;")
run("SELECT MIN(score) FROM t WHERE id <= 41;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 96 AND 116;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 97;")
run("SELECT MAX(score) FROM t WHERE id > 37;")
run("SELECT MIN(score) FROM t WHERE id <= 42;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 97 AND 117;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 98;")
run("SELECT MAX(score) FROM t WHERE id > 38;")
run("SELECT MIN(score) FROM t WHERE id <= 43;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 98 AND 118;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 99;")
run("SELECT MAX(score) FROM t WHERE id > 39;")
run("SELECT MIN(score) FROM t WHERE id <= 44;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 99 AND 119;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 60;")
run("SELECT MAX(score) FROM t WHERE id > 40;")
run("SELECT MIN(score) FROM t WHERE id <= 45;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 60 AND 80;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 61;")
run("SELECT MAX(score) FROM t WHERE id > 41;")
run("SELECT MIN(score) FROM t WHERE id <= 46;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 61 AND 81;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 62;")
run("SELECT MAX(score) FROM t WHERE id > 42;")
run("SELECT MIN(score) FROM t WHERE id <= 47;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 62 AND 82;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 63;")
run("SELECT MAX(score) FROM t WHERE id > 43;")
run("SELECT MIN(score) FROM t WHERE id <= 48;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 63 AND 83;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 64;")
run("SELECT MAX(score) FROM t WHERE id > 44;")
run("SELECT MIN(score) FROM t WHERE id <= 49;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 64 AND 84;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 65;")
run("SELECT MAX(score) FROM t WHERE id > 45;")
run("SELECT MIN(score) FROM t WHERE id <= 50;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 65 AND 85;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 66;")
run("SELECT MAX(score) FROM t WHERE id > 46;")
run("SELECT MIN(score) FROM t WHERE id <= 51;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 66 AND 86;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 67;")
run("SELECT MAX(score) FROM t WHERE id > 47;")
run("SELECT MIN(score) FROM t WHERE id <= 52;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 67 AND 87;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 68;")
run("SELECT MAX(score) FROM t WHERE id > 48;")
run("SELECT MIN(score) FROM t WHERE id <= 53;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 68 AND 88;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 69;")
run("SELECT MAX(score) FROM t WHERE id > 49;")
run("SELECT MIN(score) FROM t WHERE id <= 54;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 69 AND 89;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 70;")
run("SELECT MAX(score) FROM t WHERE id > 50;")
run("SELECT MIN(score) FROM t WHERE id <= 55;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 70 AND 90;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 71;")
run("SELECT MAX(score) FROM t WHERE id > 51;")
run("SELECT MIN(score) FROM t WHERE id <= 56;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 71 AND 91;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 72;")
run("SELECT MAX(score) FROM t WHERE id > 52;")
run("SELECT MIN(score) FROM t WHERE id <= 57;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 72 AND 92;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 73;")
run("SELECT MAX(score) FROM t WHERE id > 53;")
run("SELECT MIN(score) FROM t WHERE id <= 58;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 73 AND 93;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 74;")
run("SELECT MAX(score) FROM t WHERE id > 54;")
run("SELECT MIN(score) FROM t WHERE id <= 59;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 74 AND 94;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 75;")
run("SELECT MAX(score) FROM t WHERE id > 55;")
run("SELECT MIN(score) FROM t WHERE id <= 60;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 75 AND 95;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 76;")
run("SELECT MAX(score) FROM t WHERE id > 56;")
run("SELECT MIN(score) FROM t WHERE id <= 61;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 76 AND 96;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 77;")
run("SELECT MAX(score) FROM t WHERE id > 57;")
run("SELECT MIN(score) FROM t WHERE id <= 62;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 77 AND 97;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 78;")
run("SELECT MAX(score) FROM t WHERE id > 58;")
run("SELECT MIN(score) FROM t WHERE id <= 63;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 78 AND 98;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 79;")
run("SELECT MAX(score) FROM t WHERE id > 59;")
run("SELECT MIN(score) FROM t WHERE id <= 64;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 79 AND 99;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 80;")
run("SELECT MAX(score) FROM t WHERE id > 60;")
run("SELECT MIN(score) FROM t WHERE id <= 65;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 80 AND 100;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 81;")
run("SELECT MAX(score) FROM t WHERE id > 61;")
run("SELECT MIN(score) FROM t WHERE id <= 66;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 81 AND 101;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 82;")
run("SELECT MAX(score) FROM t WHERE id > 62;")
run("SELECT MIN(score) FROM t WHERE id <= 67;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 82 AND 102;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 83;")
run("SELECT MAX(score) FROM t WHERE id > 63;")
run("SELECT MIN(score) FROM t WHERE id <= 68;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 83 AND 103;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 84;")
run("SELECT MAX(score) FROM t WHERE id > 64;")
run("SELECT MIN(score) FROM t WHERE id <= 69;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 84 AND 104;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 85;")
run("SELECT MAX(score) FROM t WHERE id > 65;")
run("SELECT MIN(score) FROM t WHERE id <= 70;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 85 AND 105;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 86;")
run("SELECT MAX(score) FROM t WHERE id > 66;")
run("SELECT MIN(score) FROM t WHERE id <= 71;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 86 AND 106;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 87;")
run("SELECT MAX(score) FROM t WHERE id > 67;")
run("SELECT MIN(score) FROM t WHERE id <= 72;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 87 AND 107;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 88;")
run("SELECT MAX(score) FROM t WHERE id > 68;")
run("SELECT MIN(score) FROM t WHERE id <= 73;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 88 AND 108;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 89;")
run("SELECT MAX(score) FROM t WHERE id > 69;")
run("SELECT MIN(score) FROM t WHERE id <= 74;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 89 AND 109;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 90;")
run("SELECT MAX(score) FROM t WHERE id > 70;")
run("SELECT MIN(score) FROM t WHERE id <= 75;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 90 AND 110;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 91;")
run("SELECT MAX(score) FROM t WHERE id > 71;")
run("SELECT MIN(score) FROM t WHERE id <= 76;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 91 AND 111;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 92;")
run("SELECT MAX(score) FROM t WHERE id > 72;")
run("SELECT MIN(score) FROM t WHERE id <= 77;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 92 AND 112;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 93;")
run("SELECT MAX(score) FROM t WHERE id > 73;")
run("SELECT MIN(score) FROM t WHERE id <= 78;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 93 AND 113;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 94;")
run("SELECT MAX(score) FROM t WHERE id > 74;")
run("SELECT MIN(score) FROM t WHERE id <= 79;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 94 AND 114;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 95;")
run("SELECT MAX(score) FROM t WHERE id > 0;")
run("SELECT MIN(score) FROM t WHERE id <= 5;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 95 AND 115;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 96;")
run("SELECT MAX(score) FROM t WHERE id > 1;")
run("SELECT MIN(score) FROM t WHERE id <= 6;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 96 AND 116;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 97;")
run("SELECT MAX(score) FROM t WHERE id > 2;")
run("SELECT MIN(score) FROM t WHERE id <= 7;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 97 AND 117;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 98;")
run("SELECT MAX(score) FROM t WHERE id > 3;")
run("SELECT MIN(score) FROM t WHERE id <= 8;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 98 AND 118;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 99;")
run("SELECT MAX(score) FROM t WHERE id > 4;")
run("SELECT MIN(score) FROM t WHERE id <= 9;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 99 AND 119;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 60;")
run("SELECT MAX(score) FROM t WHERE id > 5;")
run("SELECT MIN(score) FROM t WHERE id <= 10;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 60 AND 80;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 61;")
run("SELECT MAX(score) FROM t WHERE id > 6;")
run("SELECT MIN(score) FROM t WHERE id <= 11;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 61 AND 81;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 62;")
run("SELECT MAX(score) FROM t WHERE id > 7;")
run("SELECT MIN(score) FROM t WHERE id <= 12;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 62 AND 82;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 63;")
run("SELECT MAX(score) FROM t WHERE id > 8;")
run("SELECT MIN(score) FROM t WHERE id <= 13;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 63 AND 83;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 64;")
run("SELECT MAX(score) FROM t WHERE id > 9;")
run("SELECT MIN(score) FROM t WHERE id <= 14;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 64 AND 84;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 65;")
run("SELECT MAX(score) FROM t WHERE id > 10;")
run("SELECT MIN(score) FROM t WHERE id <= 15;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 65 AND 85;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 66;")
run("SELECT MAX(score) FROM t WHERE id > 11;")
run("SELECT MIN(score) FROM t WHERE id <= 16;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 66 AND 86;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 67;")
run("SELECT MAX(score) FROM t WHERE id > 12;")
run("SELECT MIN(score) FROM t WHERE id <= 17;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 67 AND 87;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 68;")
run("SELECT MAX(score) FROM t WHERE id > 13;")
run("SELECT MIN(score) FROM t WHERE id <= 18;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 68 AND 88;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 69;")
run("SELECT MAX(score) FROM t WHERE id > 14;")
run("SELECT MIN(score) FROM t WHERE id <= 19;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 69 AND 89;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 70;")
run("SELECT MAX(score) FROM t WHERE id > 15;")
run("SELECT MIN(score) FROM t WHERE id <= 20;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 70 AND 90;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 71;")
run("SELECT MAX(score) FROM t WHERE id > 16;")
run("SELECT MIN(score) FROM t WHERE id <= 21;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 71 AND 91;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 72;")
run("SELECT MAX(score) FROM t WHERE id > 17;")
run("SELECT MIN(score) FROM t WHERE id <= 22;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 72 AND 92;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 73;")
run("SELECT MAX(score) FROM t WHERE id > 18;")
run("SELECT MIN(score) FROM t WHERE id <= 23;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 73 AND 93;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 74;")
run("SELECT MAX(score) FROM t WHERE id > 19;")
run("SELECT MIN(score) FROM t WHERE id <= 24;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 74 AND 94;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 75;")
run("SELECT MAX(score) FROM t WHERE id > 20;")
run("SELECT MIN(score) FROM t WHERE id <= 25;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 75 AND 95;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 76;")
run("SELECT MAX(score) FROM t WHERE id > 21;")
run("SELECT MIN(score) FROM t WHERE id <= 26;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 76 AND 96;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 77;")
run("SELECT MAX(score) FROM t WHERE id > 22;")
run("SELECT MIN(score) FROM t WHERE id <= 27;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 77 AND 97;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 78;")
run("SELECT MAX(score) FROM t WHERE id > 23;")
run("SELECT MIN(score) FROM t WHERE id <= 28;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 78 AND 98;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 79;")
run("SELECT MAX(score) FROM t WHERE id > 24;")
run("SELECT MIN(score) FROM t WHERE id <= 29;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 79 AND 99;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 80;")
run("SELECT MAX(score) FROM t WHERE id > 25;")
run("SELECT MIN(score) FROM t WHERE id <= 30;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 80 AND 100;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 81;")
run("SELECT MAX(score) FROM t WHERE id > 26;")
run("SELECT MIN(score) FROM t WHERE id <= 31;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 81 AND 101;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 82;")
run("SELECT MAX(score) FROM t WHERE id > 27;")
run("SELECT MIN(score) FROM t WHERE id <= 32;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 82 AND 102;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 83;")
run("SELECT MAX(score) FROM t WHERE id > 28;")
run("SELECT MIN(score) FROM t WHERE id <= 33;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 83 AND 103;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 84;")
run("SELECT MAX(score) FROM t WHERE id > 29;")
run("SELECT MIN(score) FROM t WHERE id <= 34;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 84 AND 104;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 85;")
run("SELECT MAX(score) FROM t WHERE id > 30;")
run("SELECT MIN(score) FROM t WHERE id <= 35;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 85 AND 105;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 86;")
run("SELECT MAX(score) FROM t WHERE id > 31;")
run("SELECT MIN(score) FROM t WHERE id <= 36;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 86 AND 106;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 87;")
run("SELECT MAX(score) FROM t WHERE id > 32;")
run("SELECT MIN(score) FROM t WHERE id <= 37;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 87 AND 107;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 88;")
run("SELECT MAX(score) FROM t WHERE id > 33;")
run("SELECT MIN(score) FROM t WHERE id <= 38;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 88 AND 108;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 89;")
run("SELECT MAX(score) FROM t WHERE id > 34;")
run("SELECT MIN(score) FROM t WHERE id <= 39;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 89 AND 109;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 90;")
run("SELECT MAX(score) FROM t WHERE id > 35;")
run("SELECT MIN(score) FROM t WHERE id <= 40;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 90 AND 110;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 91;")
run("SELECT MAX(score) FROM t WHERE id > 36;")
run("SELECT MIN(score) FROM t WHERE id <= 41;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 91 AND 111;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 92;")
run("SELECT MAX(score) FROM t WHERE id > 37;")
run("SELECT MIN(score) FROM t WHERE id <= 42;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 92 AND 112;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 93;")
run("SELECT MAX(score) FROM t WHERE id > 38;")
run("SELECT MIN(score) FROM t WHERE id <= 43;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 93 AND 113;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 94;")
run("SELECT MAX(score) FROM t WHERE id > 39;")
run("SELECT MIN(score) FROM t WHERE id <= 44;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 94 AND 114;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 95;")
run("SELECT MAX(score) FROM t WHERE id > 40;")
run("SELECT MIN(score) FROM t WHERE id <= 45;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 95 AND 115;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 96;")
run("SELECT MAX(score) FROM t WHERE id > 41;")
run("SELECT MIN(score) FROM t WHERE id <= 46;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 96 AND 116;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 97;")
run("SELECT MAX(score) FROM t WHERE id > 42;")
run("SELECT MIN(score) FROM t WHERE id <= 47;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 97 AND 117;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 98;")
run("SELECT MAX(score) FROM t WHERE id > 43;")
run("SELECT MIN(score) FROM t WHERE id <= 48;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 98 AND 118;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 99;")
run("SELECT MAX(score) FROM t WHERE id > 44;")
run("SELECT MIN(score) FROM t WHERE id <= 49;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 99 AND 119;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 60;")
run("SELECT MAX(score) FROM t WHERE id > 45;")
run("SELECT MIN(score) FROM t WHERE id <= 50;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Alice';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 60 AND 80;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 61;")
run("SELECT MAX(score) FROM t WHERE id > 46;")
run("SELECT MIN(score) FROM t WHERE id <= 51;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Bob';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 61 AND 81;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 62;")
run("SELECT MAX(score) FROM t WHERE id > 47;")
run("SELECT MIN(score) FROM t WHERE id <= 52;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Charlie';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 62 AND 82;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 63;")
run("SELECT MAX(score) FROM t WHERE id > 48;")
run("SELECT MIN(score) FROM t WHERE id <= 53;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'David';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 63 AND 83;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 64;")
run("SELECT MAX(score) FROM t WHERE id > 49;")
run("SELECT MIN(score) FROM t WHERE id <= 54;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Eve';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 64 AND 84;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("SELECT COUNT(*) FROM t WHERE score > 65;")
run("SELECT MAX(score) FROM t WHERE id > 50;")
run("SELECT MIN(score) FROM t WHERE id <= 55;")
run("SELECT SUM(score) FROM t WHERE category = 'Math';")
run("SELECT AVG(score) FROM t WHERE name = 'Frank';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 65 AND 85;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Math';")
run("SELECT COUNT(*) FROM t WHERE score > 66;")
run("SELECT MAX(score) FROM t WHERE id > 51;")
run("SELECT MIN(score) FROM t WHERE id <= 56;")
run("SELECT SUM(score) FROM t WHERE category = 'Physics';")
run("SELECT AVG(score) FROM t WHERE name = 'Grace';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 66 AND 86;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Physics';")
run("SELECT COUNT(*) FROM t WHERE score > 67;")
run("SELECT MAX(score) FROM t WHERE id > 52;")
run("SELECT MIN(score) FROM t WHERE id <= 57;")
run("SELECT SUM(score) FROM t WHERE category = 'Chemistry';")
run("SELECT AVG(score) FROM t WHERE name = 'Henry';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 67 AND 87;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Chemistry';")
run("SELECT COUNT(*) FROM t WHERE score > 68;")
run("SELECT MAX(score) FROM t WHERE id > 53;")
run("SELECT MIN(score) FROM t WHERE id <= 58;")
run("SELECT SUM(score) FROM t WHERE category = 'Biology';")
run("SELECT AVG(score) FROM t WHERE name = 'Ivy';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 68 AND 88;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'Biology';")
run("SELECT COUNT(*) FROM t WHERE score > 69;")
run("SELECT MAX(score) FROM t WHERE id > 54;")
run("SELECT MIN(score) FROM t WHERE id <= 59;")
run("SELECT SUM(score) FROM t WHERE category = 'CS';")
run("SELECT AVG(score) FROM t WHERE name = 'Jack';")
run("SELECT COUNT(id) FROM t WHERE score BETWEEN 69 AND 89;")
run("SELECT MAX(id), MIN(id) FROM t WHERE category = 'CS';")
run("CREATE TABLE empty_t (id INT, val FLOAT);")
run("SELECT COUNT(*) FROM empty_t;")
run("SELECT MAX(val) FROM empty_t;")
run("SELECT MIN(val) FROM empty_t;")
run("SELECT SUM(val) FROM empty_t;")
run("SELECT AVG(val) FROM empty_t;")
run("DROP TABLE empty_t;")
run("DROP TABLE t;")
run("SELECT COUNT(*) AS total FROM t;")
proc.send_signal(signal.SIGINT)
try:
    proc.wait(timeout=5)
except:
    proc.kill()

if failures:
    print(f"\nFAILED: {len(failures)} out of {sql_count} SQL")
    for idx, desc, sql, resp in failures[:5]:
        print(f"  @{idx} {desc}: {sql[:80]}...")
        print(f"    -> {resp[:120]}")
    sys.exit(1)
else:
    print(f"PASS: {sql_count} SQL executed, 0 failures")
